### ISSUE TITLE
Initial release plan

### ISSUE THREAD

**Issue by ianmkenney** [lilyminium/mdanalysis-sphinx-theme#19]
@lilyminium, can we plan for an initial release? I would like to begin using this project in my MDAKits ASAP using a pip install. For now I can use the `git+` prefix, but want to move to PyPI hosted package sooner rather than later.

**Comment by lilyminium** [comment]
Could you give https://pypi.org/project/mdanalysis-sphinx-theme/0.1.1/ a try? It's an initial upload that we can iterate on with more improvements.

**Comment by lilyminium** [comment]
Trying to get it onto conda-forge too: https://github.com/conda-forge/staged-recipes/pull/23708

**Comment by lilyminium** [comment]
Closed as we now have a release up -- @ianmkenney please re-open if there are further issues.
