### ISSUE TITLE
Automatic PyPI package deployment on new release

### ISSUE THREAD

**Issue by ianmkenney** [lilyminium/mdanalysis-sphinx-theme#24]
Can we make PyPI package deployments automatic with releases?

**Comment by lilyminium** [comment]
Yes, that'd be great -- would welcome a PR to this effect, thank you! I've uploaded PYPI_UPLOAD_TOKEN and TESTPYPI_UPLOAD_TOKEN secrets.

**Comment by IAlibay** [comment]
We will have (a bit later once I've transferred: https://github.com/IAlibay/pypi-deployment) a reusable action in the mda org for pure python builds, just adding the equivalent of this deployment yaml will work from now on: https://github.com/MDAnalysis/mda-xdrlib/blob/main/.github/workflows/deploy.yaml
