### ISSUE TITLE
Incompatible with `sphinxcontrib-bibtex`?

### ISSUE THREAD

**Issue by ianmkenney** [lilyminium/mdanalysis-sphinx-theme#25]
When trying to use bibtex through the `sphinxcontrib-bibtex` extension, the previously rendered functions table failed to render.

![Screenshot 2023-08-22 at 1 03 28 PM](https://github.com/MDAnalysis/mdanalysis-sphinx-theme/assets/7085164/d4f8420c-4653-4d0c-b4a6-cda662fd8ccf)

For reference, here is a capture of a working version

![image](https://github.com/MDAnalysis/mdanalysis-sphinx-theme/assets/7085164/e919dc24-d7c8-4185-9093-1049ffbc1bdb)

It appears that the div containing the table (`<div class="wy-table-responsive"><table class="autosummary longtable docutils align-default">...`) is outside of the main content.

I see that in the example documentation for this repo that citations are included directly in the docstrings.

**Comment by ianmkenney** [comment]
At the time of writing these defects can be found in the [mdaencore docs](https://www.mdanalysis.org/mdaencore/autosummary/mdaencore.similarity.html#module-mdaencore.similarity)

**Comment by lilyminium** [comment]
Do you have an example of it working? I'm curious how the bibtex changes the formatting so much.

**Comment by ianmkenney** [comment]
I haven't been able to get it to work, unfortunately.

**Comment by lilyminium** [comment]
Sorry, I meant -- do you have an online example of the table getting rendered pre-bibtex?

**Comment by ianmkenney** [comment]
Ah, I see. There isn't one 'online' right now, but you can look in the artifact from this run: 

https://github.com/MDAnalysis/mdaencore/actions/runs/5941333766

**Comment by lilyminium** [comment]
We should use the `footbibliography` directive to resolve this kind of thing: https://github.com/MDAnalysis/mdaencore/pull/13

**Comment by lilyminium** [comment]
Resolved by #26.
