### ISSUE TITLE
Document how to work with sphinxcontrib-bibtex

### ISSUE THREAD

**Issue by lilyminium** [lilyminium/mdanalysis-sphinx-theme#26]
I think appropriate guidelines would be:
- for an internal module where you think a table may get rendered through autosummary, use `footbibliography`, the directive for local bibs
- for an overall references page for the entire module: use `bibliography`. The issue in #25 was that a table got incorrectly rendered *after* the correctly rendered bibliography, so as long as we take care not to use global references in a module, I think we will avoid it in the future.
For reference, the user guide has a global bibliography: https://userguide.mdanalysis.org/stable/references.html

Also we should pin to bibtex>2.0 where the footbib was first introduced

**Comment by ianmkenney** [comment]
@lilyminium, see https://github.com/MDAnalysis/mdaencore/pull/17, most likely relevant
