### ISSUE TITLE
Diagnose and fix submodule inclusion in pypi deployment

### ISSUE THREAD

**Issue by lilyminium** [lilyminium/mdanalysis-sphinx-theme#40]
https://github.com/MDAnalysis/mdanalysis-sphinx-theme/actions/runs/6069258433/job/16463404447

**Comment by IAlibay** [comment]
That's really odd :/

**Comment by IAlibay** [comment]
Ahhhh missing the with submodules checkout argument? wow I'm making a real mess out of that action

**Comment by lilyminium** [comment]
Ahh is that is? I'm confused because executing the action commands on my machine (TM) works fine, but maybe I configured something and forgot about it

**Comment by IAlibay** [comment]
Yeah I ran into the submodule checkout issue yesterday, threw the same error because I hadn't cloned branding
